<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG8lZTvL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG8lZTvL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerG8lZTvL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerG8lZTvL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerG8lZTvL\App_KernelDevDebugContainer([
    'container.build_hash' => 'G8lZTvL',
    'container.build_id' => '886008a2',
    'container.build_time' => 1706466221,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG8lZTvL');
