<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prestataire extends \App\Entity\Prestataire implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'adresseNum' => [parent::class, 'adresseNum', null],
        "\0".'*'."\0".'adresseRue' => [parent::class, 'adresseRue', null],
        "\0".'*'."\0".'banni' => [parent::class, 'banni', null],
        "\0".'*'."\0".'email' => [parent::class, 'email', null],
        "\0".'*'."\0".'id' => [parent::class, 'id', null],
        "\0".'*'."\0".'inscription' => [parent::class, 'inscription', null],
        "\0".'*'."\0".'inscritpionConfirmation' => [parent::class, 'inscritpionConfirmation', null],
        "\0".'*'."\0".'nbEssaiesInfructueux' => [parent::class, 'nbEssaiesInfructueux', null],
        "\0".'*'."\0".'password' => [parent::class, 'password', null],
        "\0".'*'."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'commentaires' => [parent::class, 'commentaires', null],
        "\0".parent::class."\0".'image_Logo' => [parent::class, 'image_Logo', null],
        "\0".parent::class."\0".'images' => [parent::class, 'images', null],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null],
        "\0".parent::class."\0".'numTVA' => [parent::class, 'numTVA', null],
        "\0".parent::class."\0".'numTel' => [parent::class, 'numTel', null],
        "\0".parent::class."\0".'promotions' => [parent::class, 'promotions', null],
        "\0".parent::class."\0".'proposer' => [parent::class, 'proposer', null],
        "\0".parent::class."\0".'siteInternet' => [parent::class, 'siteInternet', null],
        "\0".parent::class."\0".'stages' => [parent::class, 'stages', null],
        "\0".'App\\Entity\\User'."\0".'codePostal' => ['App\\Entity\\User', 'codePostal', null],
        "\0".'App\\Entity\\User'."\0".'commune' => ['App\\Entity\\User', 'commune', null],
        "\0".'App\\Entity\\User'."\0".'localite' => ['App\\Entity\\User', 'localite', null],
        'adresseNum' => [parent::class, 'adresseNum', null],
        'adresseRue' => [parent::class, 'adresseRue', null],
        'banni' => [parent::class, 'banni', null],
        'codePostal' => ['App\\Entity\\User', 'codePostal', null],
        'commentaires' => [parent::class, 'commentaires', null],
        'commune' => ['App\\Entity\\User', 'commune', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'image_Logo' => [parent::class, 'image_Logo', null],
        'images' => [parent::class, 'images', null],
        'inscription' => [parent::class, 'inscription', null],
        'inscritpionConfirmation' => [parent::class, 'inscritpionConfirmation', null],
        'localite' => ['App\\Entity\\User', 'localite', null],
        'nbEssaiesInfructueux' => [parent::class, 'nbEssaiesInfructueux', null],
        'nom' => [parent::class, 'nom', null],
        'numTVA' => [parent::class, 'numTVA', null],
        'numTel' => [parent::class, 'numTel', null],
        'password' => [parent::class, 'password', null],
        'promotions' => [parent::class, 'promotions', null],
        'proposer' => [parent::class, 'proposer', null],
        'roles' => [parent::class, 'roles', null],
        'siteInternet' => [parent::class, 'siteInternet', null],
        'stages' => [parent::class, 'stages', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
