<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commentaire extends \App\Entity\Commentaire implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'abuses' => [parent::class, 'abuses', null],
        "\0".parent::class."\0".'contenu' => [parent::class, 'contenu', null],
        "\0".parent::class."\0".'cote' => [parent::class, 'cote', null],
        "\0".parent::class."\0".'encodage' => [parent::class, 'encodage', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'internaute' => [parent::class, 'internaute', null],
        "\0".parent::class."\0".'prestataire' => [parent::class, 'prestataire', null],
        "\0".parent::class."\0".'titre' => [parent::class, 'titre', null],
        'abuses' => [parent::class, 'abuses', null],
        'contenu' => [parent::class, 'contenu', null],
        'cote' => [parent::class, 'cote', null],
        'encodage' => [parent::class, 'encodage', null],
        'id' => [parent::class, 'id', null],
        'internaute' => [parent::class, 'internaute', null],
        'prestataire' => [parent::class, 'prestataire', null],
        'titre' => [parent::class, 'titre', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
